book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_books')
]

daftar_belanja/urls.py
from django.urls import path
from daftar_belanja.views import *

app_name = 'daftar_belanja'

urlpatterns = [
    path('shopping_cart/', shopping_cart, name='shopping_cart'),
    path('owned_books/', owned_books, name='owned_books'),
    path('get_shopping_cart/', get_shopping_cart, name='get_shopping_cart'),
    path('get_owned_books/', get_owned_books, name='get_owned_books'),
    path('confirm_payment/', confirm_payment, name='confirm_payment'),
    path('confirm_payment_flutter/', confirm_payment_flutter, name='confirm_payment_flutter'),
    path('check_book_ownership/', check_book_ownership, name='check_book_ownership'),
    path('add_to_cart/<int:id>', add_to_cart, name='add_to_cart'),
    path('add_to_cart_ajax/', add_to_cart_ajax, name='add_to_cart_ajax'),
    path('add_to_cart_flutter/', add_to_cart_flutter, name='add_to_cart_flutter'),
    path('remove_from_cart_ajax/', remove_from_cart_ajax, name='remove_from_cart_ajax'),
    path('remove_from_cart_flutter/', remove_from_cart_flutter, name='remove_from_cart_flutter'),
    path('delete_book_ajax/', delete_book_ajax, name='delete_book_ajax'),
    path('delete_book_flutter/', delete_book_flutter, name='delete_book_flutter'),
]

katalog_buku/urls.py
from django.urls import path
from katalog_buku.views import show_katalog, show_book_page, add_book_katalog, get_product_json, delete_book_katalog, add_book_to_rak, show_json

app_name = 'katalog_buku'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
    path('book/<int:id>/', show_book_page, name='show_book'),
    path('add-book-katalog/', add_book_katalog, name='add_book_katalog'),
    path('delete-book-katalog/<int:id>', delete_book_katalog, name='delete_book_katalog'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('book/<int:id>/<int:rak_id>/', add_book_to_rak, name='add_book_to_rak'),
    path('json/', show_json, name='show_json'),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('create_account/', create_account, name='create_account'),
    # path('get_accounts/', get_accounts_json, name='get_accounts_json'),
]

page_turner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('', include('main.urls')),
    path("api/books/", include("book.urls")),
    path("review/", include("review.urls")),
    path('daftar_belanja/', include('daftar_belanja.urls')),
    path('katalog/', include("katalog_buku.urls")),
    path("rak_buku/", include("rak_buku.urls")),
    path('auth/', include('authentication.urls')),
]

rak_buku/urls.py
from django.urls import path
from rak_buku.views import *


app_name = 'rak_buku'

urlpatterns = [
    path('', show_rak, name='show_rak'),
    path('<int:id>/', show_rak_by_id, name='show_rak_by_id'), 
    path('get-rak/', get_rak_json, name='get_rak_json'),
    path('get-rak/<int:id>/', get_rak_json_by_id, name='get_rak_json_by_id'),
    path('edit-rak/<int:id>/', edit_rak, name='edit_rak'),
    path('delete-rak/<int:id>/', delete_rak, name='delete_rak'),
    path('create-ajax/', add_rak_ajax, name='add_rak_ajax'),

    path('get-rak/<int:id>/list-book', get_book_json_by_id, name='get_book_json_by_id'),
    path('delete-book/<int:rak_id>/<int:book_id>/', delete_book, name='delete_book'),

    path('get-rak/flutter', get_rak_json_all, name='get_rak_json_all'),

]

wishlist/urls.py
from django.urls import path
from wishlist.views import add_notes_flutter, add_to_wishlist, add_to_wishlist_flutter, delete_book_flutter, delete_note, delete_note_flutter,  show_wishlist,  delete_book, get_wishlist_items, add_notes, show_notes,get_notes

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('add_to_wishlist/<int:book_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('delete_book/<int:book_id>/', delete_book, name='delete_book'),
    path('get_wishlist_items/', get_wishlist_items, name='get_wishlist_items'),
    path('add_notes/', add_notes, name='add_notes'),
    path('show_notes/', show_notes, name='show_notes'),
    path('get_notes/', get_notes, name='get_notes'),
    path('add_notes_flutter/', add_notes_flutter, name='add_notes_flutter'),
    path('delete_book_flutter/', delete_book_flutter, name='delete_book_flutter'),
    path('add_to_wishlist_flutter/', add_to_wishlist_flutter, name='add_to_wishlist_flutter'),
    path('delete_note/<int:note_id>/', delete_note, name='delete_note'),
    path('delete_note_flutter/', delete_note_flutter, name='delete_note_flutter'),


    
]

rak_buku/models.py
from django.db import models
from main.models import Account
from book.models import Book
from django.forms import ModelForm

# Create your models here.
class Rak(models.Model):
    name = models.CharField(max_length=16)
    description = models.TextField()
    user = models.ForeignKey(Account, on_delete=models.CASCADE) 
    books = models.ManyToManyField(Book)


class RakForm(ModelForm):
    class Meta:
        model = Rak
        fields = ["name", "description"]

rak_buku/forms.py
from django.forms import ModelForm
from rak_buku.models import Rak

class RakForm(ModelForm):
    class Meta:
        model = Rak
        fields = ["name", "description"]

rak_buku/views.py
from django.shortcuts import render, redirect
from rak_buku.models import Rak, RakForm
from main.models import Account
from book.models import Book
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect
from django.http import JsonResponse
import json
from django.core.serializers import serialize


# Create your views here.
def show_rak(request):
    all_rak = Rak.objects.all()
    user = Account.objects.get(user=request.user)
    user_rak = Rak.objects.filter(user=user)

    context = {
        'all_rak': all_rak,
        'user_rak': user_rak,
        'user': user
    }

    return render(request, "menu_rak.html", context)

def show_rak_by_id(request, id):
    rak = Rak.objects.get(pk=id)
    books_in_rak = rak.books.all()

    context = {
        'name': rak.name,
        'description': rak.description,
        'user': rak.user.full_name,
        'books': books_in_rak,
        'rak':rak
    }

    return render(request, "rak_buku.html", context)

def get_rak_json(request):
    user = Account.objects.get(user=request.user)
    user_rak = Rak.objects.filter(user=user)  # Filter Rak objects by the associated Account
    return HttpResponse(serializers.serialize('json', user_rak))

def get_book_json_by_id(request, id):
    rak = Rak.objects.get(pk=id)
    books = rak.books.all()

    # Serialize the queryset directly
    json_data = serialize('json', books)

    return HttpResponse(json_data, content_type='application/json')
def get_rak_json_by_id(request, id):
    rak = Rak.objects.filter(pk=id)  # Filter Rak objects by the associated Account
    return HttpResponse(serializers.serialize('json', rak))

def get_rak_json_all(request):
    rak = Rak.objects.all() # Filter Rak objects by the associated Account
    return HttpResponse(serializers.serialize('json', rak))

@csrf_exempt
def add_rak_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        description = request.POST.get("description")
        user = Account.objects.get(user=request.user)

        new_rak = Rak(name=name, description=description, user=user)
        new_rak.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def edit_rak(request, id):
    rak = Rak.objects.get(pk=id)

    if request.method == 'POST':
        name = request.POST.get("name")
        description = request.POST.get("description")
        user = Account.objects.get(user=request.user)

        rak.name = name
        rak.description = description
        rak.save()

        return HttpResponseRedirect(reverse('rak_buku:show_rak_by_id', args=[id]))
    return HttpResponseNotFound()

def delete_book(request, rak_id, book_id):
        rak = Rak.objects.get(pk=rak_id)
        book = Book.objects.get(pk=book_id)

        rak.books.remove(book)

        return HttpResponseRedirect(reverse('rak_buku:show_rak_by_id', kwargs={'id': rak_id,}))

def delete_rak(request, id):
        rak = Rak.objects.get(pk=id)

        rak.delete()

        return HttpResponseRedirect(reverse('rak_buku:show_rak'))

rak_buku/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <style>
            @font-face {
                font-family: 'LeagueSpartan Medium';
                src: url("{% static 'font/LeagueSpartan-Medium.ttf' %}");
            }

            @font-face {
                font-family: 'LeagueSpartan Thin';
                src: url("{% static 'font/LeagueSpartan-Thin.ttf' %}");
            }
        </style>
        {% block meta %}
        {% endblock meta %}
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

rak_buku/templates/menu_rak.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}
<style>
    #image {
        background: linear-gradient( rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.85) ), url(https://cdn.fstoppers.com/styles/full/s3/photos/2019/05/e1c586532fcb6672fac6d7a8cfa7a1b8.jpg?itok=t9H-u__W);
        background-position: center;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        height: auto;
    }
    @font-face {
                font-family: 'LeagueSpartan Medium';
                src: url("{% static 'font/LeagueSpartan-Medium.ttf' %}");
            }

    @font-face {
        font-family: 'LeagueSpartan Thin';
        src: url("{% static 'font/LeagueSpartan-Thin.ttf' %}");
    }
</style>
<nav class="navbar navbar-expand-lg bg-light bg-gradient fixed-top">
    <div class="container-fluid mx-5">
        <span class="navbar-brand mb-0 h1">PageTurner</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'katalog_buku:show_katalog' %}">Catalogue</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'daftar_belanja:owned_books' %}">My Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'daftar_belanja:shopping_cart' %}">Shopping Cart</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'rak_buku:show_rak' %}">Library</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'wishlist:show_wishlist' %}">Wishlist</a>
                </li>
            </ul>
        </div>
        <a href="{% url 'main:logout_user' %}" style="text-decoration: none;">
            <button class="btn btn-outline-danger ms-3 me-2">Logout</button>
        </a>
        <form class="d-flex ms-2 me-5" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</nav>
<br>
<div class="container-flex mt-5">
    <div class="d-flex mb-4 gap-3">
        <div class="d-flex">
        <h1 class="display-1 text-dark text-center my-0 mx-5" style="font-family: 'LeagueSpartan Medium'; letter-spacing: 3px; font-size: 3vw;">Your Library</h1>
        <button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add New Library</button>
        </div>
    </div>
    <div id="image">
        <div id="list_rak"></div>
    <hr class="mb-4 mt-4">
    <div class="d-flex mb-4 gap-3" style="background-color: white;">
        <div class="d-flex mb-4 mt-4" style="background-color: white;">
            <h1 class="display-1 text-dark text-center my-0 mx-5" style="font-family: 'LeagueSpartan Medium'; letter-spacing: 3px; font-size: 3vw;">Library Recommendation</h1>
            </div>
    </div>
        {% if user.is_premium == "Y" %}
        <div class="row row-cols-1 row-cols-md-6 g-4 mx-5">
            {% for rak in all_rak %}
            <a href="{{ rak.pk }}" style="text-decoration: none; color: inherit">
            <div class="col">
            <div class="card p-0" style="width: 12rem;">
                <img src="https://imgtr.ee/images/2023/10/27/538d8ef9d1a3e50e42b9c8709a408280.jpeg" class="card-img-top" alt="...">
                <div class="card-footer" style="font-family: 'LeagueSpartan Medium';">{{ rak.name }}</div>
            </div>
            </div>
            </a>
            {% endfor %}
        <div class="mb-4"></div>
        {% else %}
        <div class="container" style="padding: 100px;">
            <h1 class="pb-4" style= "font-family: 'LeagueSpartan Thin'; letter-spacing: 3px; font-size: 2vw; color: white; padding: 100px 100px 0px 40px; margin: 0px 0px 0px 40px;">Upgrade your account to Premium to see other users' libraries</h1>
        </div>
        {% endif %}
        
        </div>
</div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Library</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-4">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-4">
                        <label for "description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add</button>
            </div>
        </div>
    </div>
</div>

<script>
    async function getRak() {
        return fetch("{% url 'rak_buku:get_rak_json' %}").then((res) => res.json());
    }

    async function refreshRak() {
        document.getElementById("list_rak").innerHTML = "";
        const rak = await getRak();
        let htmlString = '';
        
        if (rak.length > 0) {
            htmlString += '<div class="row row-cols-1 row-cols-md-6 g-4 mx-5 mt-4">';
            
            rak.forEach((item) => {
                htmlString += `
                    <a href="${item.pk}" style="text-decoration: none; color: inherit">
                        <div class="col">
                            <div class="card">
                                <img src="https://imgtr.ee/images/2023/10/27/538d8ef9d1a3e50e42b9c8709a408280.jpeg" class="card-img-top" alt="...">
                                <div class="card-footer"class="card-text" style="font-family: 'LeagueSpartan Medium';">${item.fields.name}</div>
                            </div>
                        </div>
                    </a>
                `;
            });
            
            htmlString += '</div>';
        } else {
            htmlString += `
                <div class="container" style="padding: 100px;">
                    <h1 class="pb-4" style="font-family: 'LeagueSpartan Thin'; letter-spacing: 3px; font-size: 2vw; color: white; padding: 100px 100px 0px 40px; margin: 0px 0px 0px 40px;">You don't have a library. Create one!</h1>
                </div>
            `;
        }
        
        document.getElementById("list_rak").innerHTML = htmlString;
    }


    refreshRak();

    function addRak() {
        fetch("{% url 'rak_buku:add_rak_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshRak)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addRak
</script>

{% endblock content %}

rak_buku/templates/rak_buku.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}
<style>
    @font-face {
                font-family: 'LeagueSpartan Medium';
                src: url("{% static 'font/LeagueSpartan-Medium.ttf' %}");
            }

    @font-face {
        font-family: 'LeagueSpartan Thin';
        src: url("{% static 'font/LeagueSpartan-Thin.ttf' %}");
    }
</style>
<nav class="navbar navbar-expand-lg bg-light bg-gradient fixed-top">
    <div class="container-fluid mx-5">
        <span class="navbar-brand mb-0 h1">PageTurner</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'katalog_buku:show_katalog' %}">Catalogue</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'daftar_belanja:owned_books' %}">My Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'daftar_belanja:shopping_cart' %}">Shopping Cart</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'rak_buku:show_rak' %}">Library</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'wishlist:show_wishlist' %}">Wishlist</a>
                </li>
            </ul>
        </div>
        <a href="{% url 'main:logout_user' %}" style="text-decoration: none;">
            <button class="btn btn-outline-danger ms-3 me-2">Logout</button>
        </a>
        <form class="d-flex ms-2 me-5" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</nav>
<body>
<br>
<br>
<div style="padding: 40px;">
  <div class="card p-0">
    <div class="d-flex flex-row">
      <img src="https://imgtr.ee/images/2023/10/27/538d8ef9d1a3e50e42b9c8709a408280.jpeg" style="width: 12rem; padding: 20px;" alt="...">
    <div class="card-body">
      <h5 class="card-title" style="font-family: 'LeagueSpartan Medium'; letter-spacing: 3px; font-size: 32px;">{{ name }}</h5>
      <p class="card-text" style= "font-family: 'LeagueSpartan Thin'; letter-spacing: 3px; font-size: 20px;">{{ description }}</p>
      <p class="card-text"><small class="text-body-secondary">Created by: {{ user }}</small></p>
        <button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Edit</button>
        <a href="{% url 'rak_buku:delete_rak' rak.pk%}" style="text-decoration: none;">
          <button class="btn btn-outline-danger ms-3 me-2">Delete Library</button>
      </a>
    </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Library</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form id="form" method="post" action="{% url 'rak_buku:edit_rak' id=rak.pk %}">
                  {% csrf_token %}
                  <div class="mb-4">
                      <label for="name" class="col-form-label">Name:</label>
                      <input type="text" class="form-control" id="name" name="name" value="{{ rak.name }}"></input>
                  </div>
                  <div class="mb-4">
                      <label for="description" class="col-form-label">Description:</label>
                      <textarea class="form-control" id="description" name="description">{{ rak.description }}</textarea>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary" id="button_edit">Edit</button>
                  </div>
              </form>
          </div>
      </div>
  </div>
</div>
<div style="padding: 0px 40px 0px 40px;">
  <table class="table" style="vertical-align: middle; ">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Judul</th>
            <th scope="col">Penulis</th>
            <th scope="col">Tahun</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for item in books %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.book_title }}</td>
            <td>{{ item.book_author }}</td>
            <td>{{ item.year_of_publication }}</td>
            <td style="text-align: right;"><a href="{% url 'rak_buku:delete_book' rak_id=rak.pk book_id=item.pk %}">
              <button class="btn btn-outline-danger ms-3 me-2">Delete</button
            </a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</body>
{% endblock content %}