book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_books')
]

katalog_buku/urls.py
from django.urls import path
from katalog_buku.views import show_katalog, show_book_page, add_book_katalog, get_product_json, delete_book_katalog, add_book_to_rak, show_json

app_name = 'katalog_buku'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
    path('book/<int:id>/', show_book_page, name='show_book'),
    path('add-book-katalog/', add_book_katalog, name='add_book_katalog'),
    path('delete-book-katalog/<int:id>', delete_book_katalog, name='delete_book_katalog'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('book/<int:id>/<int:rak_id>/', add_book_to_rak, name='add_book_to_rak'),
    path('json/', show_json, name='show_json'),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('create_account/', create_account, name='create_account'),
    # path('get_accounts/', get_accounts_json, name='get_accounts_json'),
]

page_turner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('', include('main.urls')),
    path("api/books/", include("book.urls")),
    path("review/", include("review.urls")),
    path('daftar_belanja/', include('daftar_belanja.urls')),
    path('katalog/', include("katalog_buku.urls")),
    path("rak_buku/", include("rak_buku.urls")),
    path('auth/', include('authentication.urls')),
]

rak_buku/urls.py
from django.urls import path
from rak_buku.views import *


app_name = 'rak_buku'

urlpatterns = [
    path('', show_rak, name='show_rak'),
    path('<int:id>/', show_rak_by_id, name='show_rak_by_id'), 
    path('get-rak/', get_rak_json, name='get_rak_json'),
    path('get-rak/<int:id>/', get_rak_json_by_id, name='get_rak_json_by_id'),
    path('edit-rak/<int:id>/', edit_rak, name='edit_rak'),
    path('delete-rak/<int:id>/', delete_rak, name='delete_rak'),
    path('create-ajax/', add_rak_ajax, name='add_rak_ajax'),

    path('get-rak/<int:id>/list-book', get_book_json_by_id, name='get_book_json_by_id'),
    path('delete-book/<int:rak_id>/<int:book_id>/', delete_book, name='delete_book'),

    path('get-rak/flutter', get_rak_json_all, name='get_rak_json_all'),

]

review/urls.py
from django.urls import path
from review.views import *

app_name = 'review'

urlpatterns = [
    path('<int:book_id>/', show_reviews_by_book_id, name='show_reviews_by_book_id'),
    path('json/', get_reviews_json, name='get_reviews_json'),
    path('create-review-ajax/<int:book_id>/', create_review_ajax, name="create_review_ajax"),
    path('delete-review-ajax/<int:review_id>/', delete_review_ajax, name="delete_review_ajax"),
    path('update-review-ajax/<int:review_id>/', update_review_ajax, name="update_review_ajax"),
    path('get-reviews-json-by-book-id/<int:book_id>/', get_reviews_json_by_book_id, name='get_reviews_json_by_book_id'),
    path('get-reviews-json-by-request-id/<int:book_id>/', get_reviews_json_by_request_id, name="get_reviews_json_by_request_id"),
    path('get-others-reviews-json/<int:book_id>/', get_others_reviews_json, name="get_others_reviews_json"),
    path('get-book-rating-by-book-id/<int:book_id>/', get_book_rating_by_book_id, name="get_book_rating_by_book_id"),
    path('add-review/<int:book_id>/', add_review, name="add_review")
]

wishlist/urls.py
from django.urls import path
from wishlist.views import add_notes_flutter, add_to_wishlist, add_to_wishlist_flutter, delete_book_flutter, delete_note, delete_note_flutter,  show_wishlist,  delete_book, get_wishlist_items, add_notes, show_notes,get_notes

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('add_to_wishlist/<int:book_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('delete_book/<int:book_id>/', delete_book, name='delete_book'),
    path('get_wishlist_items/', get_wishlist_items, name='get_wishlist_items'),
    path('add_notes/', add_notes, name='add_notes'),
    path('show_notes/', show_notes, name='show_notes'),
    path('get_notes/', get_notes, name='get_notes'),
    path('add_notes_flutter/', add_notes_flutter, name='add_notes_flutter'),
    path('delete_book_flutter/', delete_book_flutter, name='delete_book_flutter'),
    path('add_to_wishlist_flutter/', add_to_wishlist_flutter, name='add_to_wishlist_flutter'),
    path('delete_note/<int:note_id>/', delete_note, name='delete_note'),
    path('delete_note_flutter/', delete_note_flutter, name='delete_note_flutter'),


    
]

katalog_buku/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.http import HttpResponseRedirect
from book.models import Book
from rak_buku.models import Rak
from main.models import Account
from django.urls import reverse



def show_katalog(request):
    books = Book.objects.all()

    context = {
        'books': books,
    }
    
    return render(request, "katalog_buku.html", context)

def show_book_page(request, id):
    book = Book.objects.get(pk=id)
    user = Account.objects.get(user=request.user)
    user_rak = Rak.objects.filter(user=user)
    
    delete = False
    if user == book.user:
        delete = True

    context = {
        'book': book,
        'delete': delete,
        'user_rak': user_rak,
    }

    return render(request, "book_page.html", context)

@csrf_exempt
def add_book_katalog(request):
    if request.method == "POST":
        isbn = request.POST.get("isbn")
        book_title = request.POST.get("title")
        book_author = request.POST.get("author")
        year_of_publication = request.POST.get("year")
        publisher = request.POST.get("publisher")
        image = request.POST.get("image")
        user = Account.objects.get(user=request.user)

        new_book = Book(isbn=isbn, book_title=book_title, book_author=book_author, year_of_publication=year_of_publication, publisher=publisher, image_url_s=image, image_url_m=image, image_url_l=image, user=user)
        new_book.save()

        return HttpResponse(b"CREATED", status=201)
    
    return HttpResponseNotFound()

def delete_book_katalog(request, id):
    book = Book.objects.get(pk=id)
    user = Account.objects.get(user=request.user)
    if user == book.user:
        book.delete()
    
    return redirect('katalog_buku:show_katalog')

def get_product_json(request):
    books = Book.objects.all()
    return HttpResponse(serializers.serialize('json', books))

def add_book_to_rak(request, id, rak_id):
    book = Book.objects.get(pk=id)
    rak = Rak.objects.get(pk=rak_id)
    rak.books.add(book)

    return HttpResponseRedirect(reverse('katalog_buku:show_book', args=[id]))

def show_json(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

katalog_buku/templates/book_page.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

    <style>
        #image {
            background: linear-gradient( rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.85) ), url(https://hashtaglegend.com/storage/app/media/uploaded-files/worlds-most-beautiful-libraries-7.jpg);
            background-position: center;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            height: 50vh;
        }

        #heading-2 {
            font-family: 'LeagueSpartan Thin';
            letter-spacing: 3px;
            font-size: 2vw;
        }

        .navbar-nav .nav-item a:hover {
            color: blue;
        }

        @font-face {
            font-family: 'LeagueSpartan Medium';
            src: url("{% static 'font/LeagueSpartan-Medium.ttf' %}");
        }

        @font-face {
            font-family: 'LeagueSpartan Thin';
            src: url("{% static 'font/LeagueSpartan-Thin.ttf' %}");
        }
    </style>

    <nav class="navbar navbar-expand-lg bg-light bg-gradient">
        <div class="container-fluid mx-5">
            <a href="{% url 'katalog_buku:show_katalog' %}" style="text-decoration: none;">
                <span class="navbar-brand mb-0 h1">PageTurner</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active mb-0" href="{% url 'katalog_buku:show_katalog' %}">Catalogue</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active mb-0" href="{% url 'daftar_belanja:owned_books' %}">My Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active mb-0" href="{% url 'daftar_belanja:shopping_cart' %}">Shopping Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active mb-0" href="{% url 'rak_buku:show_rak' %}">Library</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active mb-0" href="{% url 'wishlist:show_wishlist' %}">Wishlist</a>
                    </li>
                </ul>
            </div>
            <a href="{% url 'main:logout_user' %}" style="text-decoration: none;">
                <button class="btn btn-outline-danger ms-3 me-2">Logout</button>
            </a>
        </div>
    </nav>

    <div class="container mx-3">
        <div class="container-auto">
            <div class="row justify-content-center py-5">
                <div class="col-4">
                    <img src="{{ book.image_url_l }}" style="width: 400px; height: 500px;" alt="...">
                </div>
                <div class="col-5 mx-5">
                    <h1 style="font-family: 'LeagueSpartan Medium'; letter-spacing: 3px;">{{ book.book_title }}</h1>
                    <h1 id="heading-2">{{ book.book_author }}</h1>
                    <h4 id="heading-2">ISBN: {{ book.isbn }}</h1>
                    <h4 id="heading-2">Year: {{ book.year_of_publication }}</h1>
                    <h4 id="heading-2">Publisher: {{ book.publisher }}</h1>
                </div> 
                <div class="col-1">
                    <form method="POST" action="{% url 'wishlist:add_to_wishlist' book.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Add to Wishlist</button>
                    </form>
                    <a href="{% url 'daftar_belanja:add_to_cart' book.id %}">
                        <button type="button" class="btn btn-outline-success px-4 mb-3">Add to Cart</button>
                    </a>
                    {% if delete == True %}
                        <a href="{% url 'katalog_buku:delete_book_katalog' book.id %}">
                            <button>Delete Book</button>
                        </a>
                    {% endif %}
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Add to Library
                        </button>
                        <ul class="dropdown-menu">
                            {% for rak in user_rak %}
                                <li>
                                    <a href="{% url 'katalog_buku:add_book_to_rak' id=book.pk rak_id=rak.pk %}" style="text-decoration: none; color: inherit">
                                        <button type="button" class="dropdown-item button_add">{{ rak.name }}</button>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

            <div class="mt-5">
                <a href="{% url 'review:show_reviews_by_book_id' book.pk %}">
                    <button type="button" class="btn btn-outline-warning px-4 mb-3 text-dark">See Ratings & Reviews</button>
                </a>
            </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}