book/urls.py
from django.urls import path
from book.views import get_books

app_name = 'book'

urlpatterns = [
    path('', get_books, name='get_books')
]

daftar_belanja/urls.py
from django.urls import path
from daftar_belanja.views import *

app_name = 'daftar_belanja'

urlpatterns = [
    path('shopping_cart/', shopping_cart, name='shopping_cart'),
    path('owned_books/', owned_books, name='owned_books'),
    path('get_shopping_cart/', get_shopping_cart, name='get_shopping_cart'),
    path('get_owned_books/', get_owned_books, name='get_owned_books'),
    path('confirm_payment/', confirm_payment, name='confirm_payment'),
    path('confirm_payment_flutter/', confirm_payment_flutter, name='confirm_payment_flutter'),
    path('check_book_ownership/', check_book_ownership, name='check_book_ownership'),
    path('add_to_cart/<int:id>', add_to_cart, name='add_to_cart'),
    path('add_to_cart_ajax/', add_to_cart_ajax, name='add_to_cart_ajax'),
    path('add_to_cart_flutter/', add_to_cart_flutter, name='add_to_cart_flutter'),
    path('remove_from_cart_ajax/', remove_from_cart_ajax, name='remove_from_cart_ajax'),
    path('remove_from_cart_flutter/', remove_from_cart_flutter, name='remove_from_cart_flutter'),
    path('delete_book_ajax/', delete_book_ajax, name='delete_book_ajax'),
    path('delete_book_flutter/', delete_book_flutter, name='delete_book_flutter'),
]

katalog_buku/urls.py
from django.urls import path
from katalog_buku.views import show_katalog, show_book_page, add_book_katalog, get_product_json, delete_book_katalog, add_book_to_rak, show_json

app_name = 'katalog_buku'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
    path('book/<int:id>/', show_book_page, name='show_book'),
    path('add-book-katalog/', add_book_katalog, name='add_book_katalog'),
    path('delete-book-katalog/<int:id>', delete_book_katalog, name='delete_book_katalog'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('book/<int:id>/<int:rak_id>/', add_book_to_rak, name='add_book_to_rak'),
    path('json/', show_json, name='show_json'),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('create_account/', create_account, name='create_account'),
    # path('get_accounts/', get_accounts_json, name='get_accounts_json'),
]

page_turner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('', include('main.urls')),
    path("api/books/", include("book.urls")),
    path("review/", include("review.urls")),
    path('daftar_belanja/', include('daftar_belanja.urls')),
    path('katalog/', include("katalog_buku.urls")),
    path("rak_buku/", include("rak_buku.urls")),
    path('auth/', include('authentication.urls')),
]

rak_buku/urls.py
from django.urls import path
from rak_buku.views import *


app_name = 'rak_buku'

urlpatterns = [
    path('', show_rak, name='show_rak'),
    path('<int:id>/', show_rak_by_id, name='show_rak_by_id'), 
    path('get-rak/', get_rak_json, name='get_rak_json'),
    path('get-rak/<int:id>/', get_rak_json_by_id, name='get_rak_json_by_id'),
    path('edit-rak/<int:id>/', edit_rak, name='edit_rak'),
    path('delete-rak/<int:id>/', delete_rak, name='delete_rak'),
    path('create-ajax/', add_rak_ajax, name='add_rak_ajax'),

    path('get-rak/<int:id>/list-book', get_book_json_by_id, name='get_book_json_by_id'),
    path('delete-book/<int:rak_id>/<int:book_id>/', delete_book, name='delete_book'),

    path('get-rak/flutter', get_rak_json_all, name='get_rak_json_all'),

]

wishlist/urls.py
from django.urls import path
from wishlist.views import add_notes_flutter, add_to_wishlist, add_to_wishlist_flutter, delete_book_flutter, delete_note, delete_note_flutter,  show_wishlist,  delete_book, get_wishlist_items, add_notes, show_notes,get_notes

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('add_to_wishlist/<int:book_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('delete_book/<int:book_id>/', delete_book, name='delete_book'),
    path('get_wishlist_items/', get_wishlist_items, name='get_wishlist_items'),
    path('add_notes/', add_notes, name='add_notes'),
    path('show_notes/', show_notes, name='show_notes'),
    path('get_notes/', get_notes, name='get_notes'),
    path('add_notes_flutter/', add_notes_flutter, name='add_notes_flutter'),
    path('delete_book_flutter/', delete_book_flutter, name='delete_book_flutter'),
    path('add_to_wishlist_flutter/', add_to_wishlist_flutter, name='add_to_wishlist_flutter'),
    path('delete_note/<int:note_id>/', delete_note, name='delete_note'),
    path('delete_note_flutter/', delete_note_flutter, name='delete_note_flutter'),


    
]

daftar_belanja/models.py
from django.db import models
from book.models import Book
from main.models import Account

class ShoppingCart(models.Model):
    account = models.OneToOneField(Account, on_delete=models.CASCADE)
    cart = models.ManyToManyField(Book, related_name='cart')
    owned_books = models.ManyToManyField(Book, related_name='owned_books')

daftar_belanja/forms.py
from django.forms import ModelForm
from daftar_belanja.models import ShoppingCart

class PaymentForm(ModelForm):
    class Meta:
        model = ShoppingCart 
        fields = ["receiver", "payment"]

daftar_belanja/views.py
from main.models import Account
from book.models import Book
from django.contrib.auth.models import User
from daftar_belanja.models import *
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.contrib import messages
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse
import json

@login_required(login_url='/login')
def shopping_cart(request):
    account = Account.objects.get(user=request.user)
    cart, created = ShoppingCart.objects.get_or_create(account=account)

    context = {
        'user': request.user.username,
        'account': account,
        'cart': cart.cart.all,
    }

    if not cart.cart.all():
        context['cart_empty'] = True
    else:
        context['cart_empty'] = False

    return render(request, 'shopping_cart.html', context)

@login_required(login_url='/login')
def owned_books(request):
    account = Account.objects.get(user=request.user)
    cart, created = ShoppingCart.objects.get_or_create(account=account)

    context = {
        'user': request.user.username,
        'account': account,
        'books': cart.owned_books.all,
    }

    if not cart.owned_books.all():
        context['no_books'] = True
    else:
        context['no_books'] = False

    return render(request, 'owned_books.html', context)

def get_shopping_cart(request):
    account = Account.objects.get(user=request.user)
    try:
        cart = ShoppingCart.objects.get(account=account)
        return HttpResponse(serializers.serialize('json', cart.cart.all()), content_type="application/json")
    except ShoppingCart.DoesNotExist:
        return HttpResponse(serializers.serialize('json', []), content_type="application/json")

def get_owned_books(request):
    account = Account.objects.get(user=request.user)
    try:
        cart = ShoppingCart.objects.get(account=account)
        return HttpResponse(serializers.serialize('json', cart.owned_books.all()), content_type="application/json")
    except ShoppingCart.DoesNotExist:
        return HttpResponse(serializers.serialize('json', []), content_type="application/json")

def add_to_cart(request, id):
    account = Account.objects.get(user=request.user)
    cart, created = ShoppingCart.objects.get_or_create(account=account)
    book = Book.objects.get(pk=id)
    books = Book.objects.all()

    context = {
        'books': books,
    }

    cart.cart.add(book)
    return render(request, 'katalog_buku.html', context)

@csrf_exempt
def add_to_cart_ajax(request):
    if request.method == 'POST':
        pk = json.loads(request.body).get('pk')
        account = Account.objects.get(user=request.user)
        cart, created = ShoppingCart.objects.get_or_create(account=account)
        book = Book.objects.get(pk=pk)
        cart.cart.add(book)

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def add_to_cart_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        bookID = data["bookID"]
        account = Account.objects.get(user=request.user)
        cart, created = ShoppingCart.objects.get_or_create(account=account)
        book = Book.objects.get(pk=bookID)
        cart.cart.add(book)

        return JsonResponse({"status": True,}, status=200)
    
    return JsonResponse({"status": False}, status=500)

@csrf_exempt
def remove_from_cart_ajax(request):
    if request.method == 'DELETE':
        pk = json.loads(request.body).get('pk')
        account = Account.objects.get(user=request.user)
        cart, created = ShoppingCart.objects.get_or_create(account=account)
        book = Book.objects.get(pk=pk)
        cart.cart.remove(book)
        return HttpResponse(b"DELETED", 201)

    return HttpResponseNotFound()

@csrf_exempt
def remove_from_cart_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        bookID = data["bookID"]
        account = Account.objects.get(user=request.user)
        cart, created = ShoppingCart.objects.get_or_create(account=account)
        book = Book.objects.get(pk=bookID)
        cart.cart.remove(book)
        return JsonResponse({"status": True,}, status=200)
    
    return JsonResponse({"status": False}, status=500)

@csrf_exempt
def delete_book_ajax(request):
    if request.method == 'DELETE':
        pk = json.loads(request.body).get('pk')
        account = Account.objects.get(user=request.user)
        cart, created = ShoppingCart.objects.get_or_create(account=account)
        book = Book.objects.get(pk=pk)
        cart.owned_books.remove(book)
        return HttpResponse(b"DELETED", 201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_book_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        bookID = data["bookID"]
        user = request.user
        account = Account.objects.get(user=user)
        cart, created = ShoppingCart.objects.get_or_create(account=account)
        book = Book.objects.get(pk=bookID)
        cart.owned_books.remove(book)
        return JsonResponse({"status": True,}, status=200)
    
    return JsonResponse({"status": False}, status=500)

@csrf_exempt
def confirm_payment(request):
    if request.method == 'POST':
        receiver = User.objects.get(username = request.POST.get("receiver"))
        giver = Account.objects.get(user = request.user)
        account = Account.objects.get(user = receiver)
        receiver_cart, created = ShoppingCart.objects.get_or_create(account=account)
        giver_cart, created = ShoppingCart.objects.get_or_create(account=giver)
        for book in receiver_cart.cart.all():
            receiver_cart.owned_books.add(book)

        giver_cart.cart.clear()
        
        return HttpResponse(b"CREATED", status=201)
    
    return HttpResponseNotFound()

@csrf_exempt
def confirm_payment_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        receiverName = data["username"]
        payment = data["payment"]

        receiver = User.objects.get(username = receiverName)
        giver = Account.objects.get(user = request.user)
        account = Account.objects.get(user = receiver)
        receiver_cart, created = ShoppingCart.objects.get_or_create(account=account)
        giver_cart, created = ShoppingCart.objects.get_or_create(account=giver)
        for book in receiver_cart.cart.all():
            receiver_cart.owned_books.add(book)

        giver_cart.cart.clear()
        
        return JsonResponse({
            "status": True,
            "message": "Payment with {payment} is Successful!",
        }, status=200)
    
    return JsonResponse({
        "status": False,
        "message": "Something went wrong, try again!",
    }, status=500)

@csrf_exempt
def check_book_ownership(request):
    if request.method == 'GET':
        pk = request.GET.get('pk') 

        account = Account.objects.get(user=request.user)
        book = Book.objects.get(pk=pk)
        cart, created = ShoppingCart.objects.get_or_create(account=account)
        is_owned = cart.owned_books.filter(pk=book.pk).exists()

        data = {'is_owned': is_owned}
        return JsonResponse(data)

daftar_belanja/templates/add_book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Welcome {{ user }} </h1>

    {% if account.get_is_premium %}
        <h2>Premium Account</h2>

    {% elif not account.get_is_premium %}
        <h2>Regular Account</h2>

    {% endif %}

    <p>Fullname: {{ account.full_name }}</p>
    <p>Email: {{ account.email }}</p>

    <a class="nav-link active" aria-current="page" href="{% url 'daftar_belanja:owned_books' %}">
        <button type="button" class="btn btn-primary" id="button_add">
            Owned Books
        </button>
    </a>

    <br>
    
    <a class="nav-link active" aria-current="page" href="{% url 'daftar_belanja:shopping_cart' %}">
        <button type="button" class="btn btn-primary" id="button_add">
            Look at my shopping cart
        </button>
    </a>

    <table id="book_catalogue" class="book_catalogue"></table>

    <br>

    <script>
        async function isBookOwned(pk) {
            let response = await fetch("{% url 'daftar_belanja:check_book_ownership' %}?pk=" + pk);
            let data = await response.json();
            return data.is_owned;
        }
    
        async function getBooks() {
            return fetch("{% url 'book:get_books' %}").then((res) => res.json());
        }
    
        async function refreshTable() {
            const books = await getBooks();
            const bookCatalogue = document.getElementById("book_catalogue");

            bookCatalogue.innerHTML = "";

            let htmlString = `
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Publisher</th>
                <th>Add Book</th>
            </tr>`;

            for (const item of books) {
                const isOwned = await isBookOwned(item.pk);

                const ownedString = `<a>
                        <button type="button" class="btn btn-primary" id="button_add">
                            Owned
                        </button>
                    </a>`

                htmlString += `
                \n<tr>
                    <td>${item.fields.book_title}</td>
                    <td>${item.fields.book_author}</td>
                    <td>${item.fields.isbn}</td>
                    <td>${item.fields.year_of_publication}</td>
                    <td>
                        ${isOwned ? ownedString : `
                        <a>
                            <button type="button" class="btn btn-primary" id="button_add" onclick="addToCart(${item.pk})">
                                Put in shopping cart
                            </button>
                        </a>`}
                    </td>
                </tr>`;
            }

            document.getElementById("book_catalogue").innerHTML = htmlString;
        }
    
        refreshTable();
    
        function addToCart(pk) {
            fetch("{% url 'daftar_belanja:add_to_cart' %}", {
                method: 'POST',
                body: JSON.stringify({
                    'pk': pk
                })
            })
        }
    </script>
{% endblock content %}

daftar_belanja/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        {% block meta %}
        {% endblock meta %}
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

daftar_belanja/templates/shopping_cart.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Shopping Cart - PageTurner</title>
{% endblock meta %}

{% block content %}

<style>
    #image {
        background: linear-gradient( rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.85) ), url(https://media.cntraveler.com/photos/5e73a851a32d290008f50901/16:9/w_2580,c_limit/Tianjin%20Binhai%20Library%20cr%20Ossip%20van%20Duivenbode.jpg);
        background-position: center;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        height: 50vh;
    }

    #heading-2 {
        font-family: 'LeagueSpartan Thin';
        letter-spacing: 3px;
        font-size: 2vw;
    }

    .navbar-nav .nav-item a:hover {
        color: blue;
    }

    @font-face {
        font-family: 'LeagueSpartan Medium';
        src: url("{% static 'font/LeagueSpartan-Medium.ttf' %}");
    }

    @font-face {
        font-family: 'LeagueSpartan Thin';
        src: url("{% static 'font/LeagueSpartan-Thin.ttf' %}");
    }
</style>

<nav class="navbar navbar-expand-lg bg-light bg-gradient fixed-top">
    <div class="container-fluid mx-5">
        <span class="navbar-brand mb-0 h1">PageTurner</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'katalog_buku:show_katalog' %}">Catalogue</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'daftar_belanja:owned_books' %}">My Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'daftar_belanja:shopping_cart' %}">Shopping Cart</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'rak_buku:show_rak' %}">Library</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active mb-0" href="{% url 'wishlist:show_wishlist' %}">Wishlist</a>
                </li>
            </ul>
        </div>
        <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#checkout">Checkout Cart</button>
        <a href="{% url 'main:logout_user' %}" style="text-decoration: none;">
            <button class="btn btn-outline-danger ms-3 me-2">Logout</button>
        </a>
        <form class="d-flex ms-2 me-5" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</nav>

<div class="modal fade" id="checkout" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Checkout Cart</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="payment-form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3 justify-content-center text-center">
                        <h4 style="font-weight: bold;">Please confirm your receipt</h4>
                    </div>
                    <div class="mb-3">
                        <table class="mb-3" style="margin: 0 auto;">
                            <tr>
                                <th>Title</th>
                                <th>ISBN</th>
                            </tr>
                            {% for book in cart %}
                                <tr>
                                    <td>{{ book.book_title | truncatechars:50 }}</td>
                                    <td>{{book.isbn}}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <div class="mb-3">
                        <label for="receiver" class="col-form-label" style="font-weight: bold;">Username:</label>
                        <input type="text" class="form-control" id="receiver" name="receiver"></input>
                    </div>
                    <div class="mb-3">
                        <label for="payment" class="col-form-label" style="font-weight: bold;">Payment Method:</label>
                        <select class="form-control" id="payment" name="payment">
                            <option value="Debit Card">Debit Card</option>
                            <option value="Credit Card">Credit Card</option>
                            <option value="GoPay">GoPay</option>
                            <option value="OVO">OVO</option>
                            <option value="PayPal">Paypal</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer" id="modal-payment"></div>
        </div>
    </div>
</div>

<div class="container-fluid text-center" id="image" style="padding-top: 30px;">
    <div class="row align-items-center justify-content-center" style="height: 50vh;">
        <div class="col-5">
            <div class="row">
                <h1 class="display-1 text-light my-0" style="font-family: 'LeagueSpartan Medium'; letter-spacing: 3px; font-size: 6vw;">
                    Shopping Cart
                </h1>
            </div>
            <div class="row mx-10">
                <h1 class="display-1 text-light my-0" id="heading-2">
                    Welcome {{ account.full_name }}
                </h1>
            </div>
            <div class="row mx-10">
                {% if account.get_is_premium %}
                    <h1 class="display-1 text-light my-0" id="heading-2">
                        Premium Account
                    </h1>
            
                {% elif not account.get_is_premium %}
                    <h1 class="display-1 text-light my-0" id="heading-2">
                        Regular Account
                    </h1>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container-auto text-center mt-5" style="padding-bottom: 50px;">
    <div class="book-cards">
        <div class="row gy-5 justify-content-center" id="book-cards"></div>
    </div>
</div>

<script>
    async function getShoppingCart() {
        return fetch("{% url 'daftar_belanja:get_shopping_cart' %}").then((res) => res.json())
    }

    async function refreshAfterPayment() {
        const paymentButton = document.getElementById("modal-payment")
        paymentButton.innerHTML = `
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal" onclick="confirmPayment()">Confirm Payment</button>
        `
    }

    async function refreshCards() {
        const books = await getShoppingCart()
        const bookCatalogue = document.getElementById("book-cards")

        bookCatalogue.innerHTML = "";

        let htmlString = ``;
        let totalBooks = 0;
        books.forEach((item) => {
            const bookTitles = item.fields.book_title.slice(0, 43) + "...";
            totalBooks += 1;
            htmlString += `
                <div class="col-auto mx-3">
                    <a style="text-decoration: none;" data-bs-toggle="modal" data-bs-target="#checkout${item.pk}">
                        <div class="card" style="width: 18rem; height: 30rem; box-shadow: 0px 10px 5px 0px rgba(0, 0, 0, 0.3);">
                            <img src="${ item.fields.image_url_l }" class="card-img-top" alt="..." style="width: 18rem; height: 350px;">
                            <div class="card-body">
                                <p class="card-text" style="font-family: 'LeagueSpartan Medium'; font-size: 1vw;">${bookTitles}</p>
                                <p class="card-text" style="font-family: 'LeagueSpartan Thin'; font-size: 1vw;">${item.fields.book_author}</p>
                            </div>
                        </div>
                    </a>
                </div>`

            htmlString += `
                <div class="modal fade" id="checkout${item.pk}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5 me-5" id="exampleModalLabel" style="font-family: 'LeagueSpartan Medium';">${bookTitles}</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="container text-center">
                                    <div class="row justify-content-center">
                                        <div class="col mb-3">
                                            <img src="${ item.fields.image_url_l }" class="img-fluid rounded" alt="...">
                                        </div>
                                    </div>
        
                                    <div class="row mb-3 justify-content-center text-center">
                                        <div class="col-mb-3">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel" style="font-family: 'LeagueSpartan Thin';">${item.fields.book_author}</h1>
                                        </div>
                                    </div>
        
                                </div>
                            </div>
                            <div class="modal-footer justify-content-center">
                                <a href="/katalog/book/${item.pk}/">
                                    <button type="button" class="btn btn-outline-info px-4" data-bs-dismiss="modal" onclick="">Book Details</button>
                                </a>
                                <button type="button" class="btn btn-outline-success px-4" data-bs-dismiss="modal" onclick="removeFromCart(${item.pk})">Remove from Cart</button>
                            </div>
                        </div>
                    </div>
                </div>
            `
        })

        if (totalBooks == 0) {
            htmlString += `
            <div class="row align-items-center justify-content-center" style="height: 50vh;">
                <div class="col-6">
                    <div class="row text-center" style="padding-bottom: 10px;">
                        <h1 class="display-1 text-dark my-0" style="font-family: 'LeagueSpartan Medium'; letter-spacing: 3px; font-size: 3vw;">
                            Your Shopping Cart is empty...
                        </h1>
                    </div>
                    <div class="row text-center" style="padding-bottom: 20px;">
                        <h1 class="display-1 text-dark my-0" id="heading-2">
                            Check out our extensive catalogue!
                        </h1>
                    </div>
                    <div class="row text-center">
                        <a class="btn btn-success btn-lg" href="/katalog/" role="button" style="width: 68%; margin: auto auto;">
                            Catalogue
                        </a>
                    </div>
                </div>
            </div>
            `
        }
        bookCatalogue.innerHTML = htmlString;
    }

    refreshCards();
    refreshAfterPayment();

    function removeFromCart(pk) {
        fetch("{% url 'daftar_belanja:remove_from_cart_ajax' %}", {
            method: 'DELETE',
            body: JSON.stringify({
                'pk': pk
            })
        }).then(refreshAfterPayment).then(refreshCards)
    }

    function confirmPayment() {
        fetch("{% url 'daftar_belanja:confirm_payment' %}", {
            method: 'POST',
            body: new FormData(document.querySelector('#payment-form'))
        }).then(refreshAfterPayment).then(refreshCards)

        document.getElementById("payment-form").reset()
        return false
    }
</script>

{% endblock content %}